version: "3"

services:
  redis:
    container_name: redis_server
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    environment:
      REDIS_PASSWORD: 'lhs123456'
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    volumes:
      - redis:/data
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  redis:
    driver: local